name: Deploy goose docs to GitHub Pages
on:
  push:
    branches:
      - github-pages-docs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: |
          docker run --rm -it -v ${PWD}:/docs squidfunk/mkdocs-material build
